######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 6 22:49:20 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Catcher.hpp
SOURCES += main.cpp
