######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 6 23:01:13 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += catcher.hpp painter.h
SOURCES += catcher.cpp main.cpp
